source 'https://github.com/CocoaPods/Specs.git'# 默认的 GitHub Spec

#use_frameworks!

platform :ios,'10.0'

target 'PPHud_Example' do
  pod 'PPHud', :path => '../'

  target 'PPHud_Tests' do
    inherit! :search_paths

    
  end
end
